In [24]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

x = np.random.randint(1000,size=(5,5))
print(x)
x_scale = preprocessing.scale(x)
print(x_scale)

[[661 189 810 515 585]
 [452 370 769 523 167]
 [306 337 826 664 402]
 [948 352 821 234 949]
 [943 714 637 530 828]]
[[-0.00388313 -1.17432575  0.52898782  0.15486736 -0.00424396]
 [-0.81545681 -0.12932594 -0.05091861  0.21169942 -1.4825577 ]
 [-1.38239345 -0.31985077  0.75529277  1.21336445 -0.6514483 ]
 [ 1.11057452 -0.23324858  0.68457247 -1.8413587   1.28309145]
 [ 1.09115888  1.85675104 -1.91793445  0.26142747  0.85515852]]


d:\anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)


In [35]:
x_1 = np.random.randint(1000, size=(5,5))
print(x_1)
stand_scale = preprocessing.StandardScaler().fit(x_1)
stand_scale.transform(x_1)

[[409 668 127 969 242]
 [502 769 173 257 566]
 [376 402 162 765 233]
 [551 891 590 321 519]
 [768 180 118 881 268]]


d:\anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[-0.81041445,  0.33382015, -0.5971302 ,  1.12614773, -0.84857933],
       [-0.13868055,  0.72586474, -0.34042002, -1.30065973,  1.37585192],
       [-1.04877164, -0.69869333, -0.40180724,  0.43082649, -0.91036909],
       [ 0.21524377,  1.19942355,  1.98671356, -1.08251974,  1.05317208],
       [ 1.78262287, -1.5604151 , -0.6473561 ,  0.82620524, -0.67007559]])

In [45]:
x_2 = np.array([[1,100,-100],
              [1,200,300]])
minmax = preprocessing.MinMaxScaler()
minmax.fit_transform(x_2)

d:\anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0., 0., 0.],
       [0., 1., 1.]])

In [50]:
x_3 = np.array([[1,100,-100],
              [1,200,300]])
maxabs = preprocessing.MaxAbsScaler()
x_3 = maxabs.fit_transform(x_3)
print(x_3)

[[ 1.          0.5        -0.33333333]
 [ 1.          1.          1.        ]]


In [52]:
x_4 = np.array([[1,100,-100],
              [1,200,300]])
normal = preprocessing.Normalizer().fit(x_4)
normal.transform(x_4)

array([[ 0.00707089,  0.7070891 , -0.7070891 ],
       [ 0.00277349,  0.55469806,  0.83204709]])

In [55]:
binarizer = preprocessing.Binarizer(threshold= 100).fit(x_4)
binarizer.transform(x_4)

array([[0, 0, 0],
       [0, 1, 1]])

In [72]:
x_5 = np.array([[1,2,3],
           [0,2,4],
           [1,3,5]])
onehot = preprocessing.OneHotEncoder().fit(x_5)
x_6 = np.array([[1,2,5]])
# 01 10 001
x_6 = onehot.transform(x_6).toarray()
print(x_6)

[[0. 1. 1. 0. 0. 0. 1.]]


In [81]:
imputer = preprocessing.Imputer(strategy='mean',missing_values='NaN', axis=0).fit([[1,2],
                                      [1,4],
                                       [1,6]])
imputer.transform([[np.nan,np.nan]])


array([[1., 4.]])

In [84]:
x7 = np.arange(9).reshape(3,3)
ploy = preprocessing.PolynomialFeatures(2)
x_7_ploy = ploy.fit_transform(x7)
print(x_7_ploy)

[[ 1.  0.  1.  2.  0.  0.  0.  1.  2.  4.]
 [ 1.  3.  4.  5.  9. 12. 15. 16. 20. 25.]
 [ 1.  6.  7.  8. 36. 42. 48. 49. 56. 64.]]


In [88]:
func = preprocessing.FunctionTransformer(np.log10)
print(x7)
func.transform(x7)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


d:\anaconda3\lib\site-packages\sklearn\preprocessing\_function_transformer.py:161: RuntimeWarning: divide by zero encountered in log10
  **(kw_args if kw_args else {}))


array([[      -inf, 0.        , 0.30103   ],
       [0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999]])